<?php

use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Permission;

class PermissionTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     * php artisan db:seed --class=PermissionTableSeeder
     * @return void
     */
    public function run()
    {
        $permissions = [
            //Block-20230203 Esteban Pablo
            /**
            *['name'=>'Lista de roles','category'=>'Administración del sistema'],
            *['name'=>'Crear roles','category'=>'Administración del sistema'],
            *['name'=>'Editar roles','category'=>'Administración del sistema'],
            *['name'=>'Eliminar roles','category'=>'Administración del sistema'],
            *['name'=>'Lista de solicitudes','category'=>'Otros'],
            *['name'=>'Lista de usuarios','category'=>'Gestión humana'],
            *['name'=>'Ver usuarios','category'=>'Gestión humana'],
            *['name'=>'Crear usuarios','category'=>'Gestión humana'],
            *['name'=>'Eliminar usuarios','category'=>'Gestión humana'],
            *['name'=>'Editar usuarios','category'=>'Gestión humana'],
            *['name'=>'Descargar PDF de solicitudes','category'=>'Otros'],
            *['name'=>'Digitar formulario de Permisos de trabajo','category'=>'Gestión humana'],
            *['name'=>'Digitar formulario de Inspección de equipos de protección contra caídas','category'=>'Gestión humana'],
            *['name'=>'Ver solicitudes de empleo','category'=>'Gestión humana'],
            *['name'=>'Aprobar solicitud de Permisos de trabajo','category'=>'Dirección'],
            *['name'=>'Aprobar solicitud de Inspección y protección contra caídas','category'=>'Dirección'],
            *['name'=>'Aprobar solicitud de Inspección detallada de vehículos','category'=>'Dirección'],
            *['name'=>'Digitar formulario de inspección detallada de vehículos','category'=>'Logística e infraestructura'],
            *['name'=>'Aprobar solicitud de Revisión y asignación de herramientas','category'=>'Dirección'],
            *['name'=>'Digitar formulario de Revisión y asignación de herramientas','category'=>'Ejecución de obras'],
            *['name'=>'Consultar cartelera','category'=>'Otros'],
            *['name'=>'Descargar documentos de la cartelera','category'=>'Otros'],
            *['name'=>'Editar documentos de la cartelera','category'=>'Otros'],
            *['name'=>'Eliminar documentos de la cartelera','category'=>'Otros'],
            *['name'=>'Crear documentos para la cartelera','category'=>'Otros'],
            *['name'=>'Digitar formulario de entrega de dotación personal','category'=>'Gestión humana'],
            *['name'=>'Digitar formulario de lista de verificación para el mantenimiento de computadores','category'=>'Logística e infraestructura'],
            *['name'=>'Digitar formulario de solicitud de permiso laboral o notificación de incapacidad','category'=>'Gestión humana'],
            *['name'=>'Aprobar solicitud de lista de verificación para el mantenimiento de computadores','category'=>'Dirección'],
            *['name'=>'Aprobar solicitud de entrega de dotación personal','category'=>'Dirección'],
            *['name'=>'Aprobar solicitud de permiso laboral o notificación de incapacidad','category'=>'Dirección'],
            *['name'=>'Lista de proveedores','category'=>'Dirección'],
            *['name'=>'Lista de clientes','category'=>'Servicio al cliente y garantía de obras'],
            *['name'=>'Lista de proyectos','category'=>'Ejecución de obras'],
            *['name'=>'Lista de evaluaciones de desempeño','category'=>'Gestión humana'],
            *['name'=>'Lista de evaluaciones de satisfacción del cliente','category'=>'Servicio al cliente y garantía de obras'],
            *['name'=>'Ver evaluaciones de proveedores','category'=>'Dirección'],
            *['name'=>'Configuraciones generales','category'=>'Administración del sistema'],
            *['name'=>'Configuraciones del sistema','category'=>'Administración del sistema'],
            *['name'=>'Configurar mensajes en el sistema','category'=>'Administración del sistema'],
            *['name'=>'Eliminar proyectos','category'=>'Ejecución de obras'],
            *['name'=>'Consultar permisos de trabajo','category'=>'Gestión humana'],
            *['name'=>'Consultar inspecciones de equipos de protección contra caídas','category'=>'Gestión humana'],
            *['name'=>'Consultar inspecciones detalladas de vehículos','category'=>'Logística e infraestructura'],
            *['name'=>'Consultar revisión y asignación de herramientas','category'=>'Ejecución de obras'],
            *['name'=>'Consultar entrega de dotación personal','category'=>'Gestión humana'],
            *['name'=>'Consultar listas de verificación para el mantenimiento de los computadores','category'=>'Logística e infraestructura'],
            *['name'=>'Consultar solicitud de permisos laborales o notificaciones de incapacidad médica','category'=>'Gestión humana'],
            *['name'=>'Descargar PDF de permisos de trabajo','category'=>'Gestión humana'],
            *['name'=>'Descargar PDF de inspecciones de equipos de protección contra caídas','category'=>'Gestión humana'],
            *['name'=>'Descargar PDF de inspecciones detalladas de vehículos','category'=>'Logística e infraestructura'],
            *['name'=>'Descargar PDF de revisión y asignación de herramientas','category'=>'Ejecución de obras'],
            *['name'=>'Descargar PDF de entrega de dotación personal','category'=>'Gestión humana'],
            *['name'=>'Descargar PDF de listas de verificación para el mantenimiento de los computadores','category'=>'Logística e infraestructura'],
            *['name'=>'Descargar PDF de solicitud de permisos laborales o notificaciones de incapacidad médica','category'=>'Gestión humana'],
            *['name'=>'Ver usuarios eliminados','category'=>'Gestión humana'],
            *['name'=>'Disparar evaluación de desempeño','category'=>'Gestión humana'],
            *['name'=>'Realizar llamados de atención a trabajadores','category'=>'Gestión humana'],
            *['name'=>'Restaurar usuarios eliminados','category'=>'Gestión humana'],
            *['name'=>'Ver llamados de atención','category'=>'Gestión humana'],
            *['name'=>'Disparar evaluación a proveedores','category'=>'Dirección'],
            *['name'=>'Enviar evaluación de satisfacción del cliente','category'=>'Servicio al cliente y garantía de obras'],
            *['name'=>'Evaluar evaluaciones de desempeño','category'=>'Gestión humana'],
            *['name'=>'Crear proyectos','category'=>'Ejecución de obras'],
            *['name'=>'Editar proyectos','category'=>'Ejecución de obras'],
            *['name'=>'Aprobar proyectos','category'=>'Dirección'],
            *['name'=>'Crear entrevistas','category'=>'Gestión humana'],
            *['name'=>'Lista de solicitudes de empleo','category'=>'Gestión humana'],
            *['name'=>'Ver proyectos','category'=>'Ejecución de obras'],
            *['name'=>'Lista de llamados de atención','category'=>'Gestión humana'],
            *['name'=>'Responder llamados de atención','category'=>'Gestión humana'],
            *['name'=>'Aprobar llamados de atención','category'=>'Dirección'],
            *['name'=>'Crear clientes','category'=>'Servicio al cliente y garantía de obras'],
            *['name'=>'Ver clientes','category'=>'Servicio al cliente y garantía de obras'],
            *['name'=>'Eliminar clientes','category'=>'Servicio al cliente y garantía de obras'],
            *['name'=>'Ver evaluaciones de satisfacción de los clientes','category'=>'Servicio al cliente y garantía de obras'],
            *['name'=>'Editar clientes','category'=>'Servicio al cliente y garantía de obras'],
            *['name'=>'Crear proveedores','category'=>'Dirección'],
            *['name'=>'Editar proveedores','category'=>'Dirección'],
            *['name'=>'Eliminar proveedores','category'=>'Dirección'],
            *['name'=>'Ver proveedores','category'=>'Dirección'],
            *['name'=>'Calificar evaluaciones de proveedores','category'=>'Dirección'],
            *['name'=>'Lista de evaluaciones de proveedores','category'=>'Dirección'],
            *['name'=>'Ver evaluaciones de desempeño','category'=>'Gestión humana'],
            *['name'=>'Aprobar evaluación de desempeño','category'=>'Dirección'],
            *['name'=>'Calificar evaluaciones de desempeño','category'=>'Gestión humana'],
            *['name'=>'Lista de entrevista','category'=>'Gestión humana'],
            *['name'=>'Lista de hojas de vida','category'=>'Gestión humana'],
            *['name'=>'Lista de memorandos','category'=>'Gestión humana'],
            *['name'=>'Crear memorandos','category'=>'Gestión humana'],
            *['name'=>'Ver memorandos','category'=>'Gestión humana'],
            *['name'=>'Ver entrevistas','category'=>'Gestión humana'],
            *['name'=>'Aprobar entrevistas','category'=>'Dirección'],
            *['name'=>'Editar entrevistas','category'=>'Gestión humana'],
            *['name'=>'Ver hojas de vida','category'=>'Gestión humana'],
            *['name'=>'Editar hojas de vida','category'=>'Gestión humana'],
            *['name'=>'Aprobar hojas de vida','category'=>'Dirección'],
            *['name'=>'Eliminar llamados de atención','category'=>'Gestión humana'],
            *['name'=>'Editar memorandos','category'=>'Gestión humana'],
            *['name'=>'Eliminar evaluación de proveedores','category'=>'Dirección'],
            *['name'=>'Eliminar evaluación de satisfación de clientes','category'=>'Servicio al cliente y garantía de obras'],
            *['name'=>'Eliminar memorandos','category'=>'Gestión humana'],
            *['name'=>'Configurar cargos','category'=>'Gestión humana'],
            *['name'=>'Eliminar entrevistas','category'=>'Gestión humana'],
            *['name'=>'Editar llamados de atención','category'=>'Gestión humana'],
            *['name'=>'Eliminar solicitudes de empleo','category'=>'Gestión humana'],
            *['name'=>'Eliminar hojas de vida','category'=>'Gestión humana'],
            *['name'=>'Crear hojas de vida','category'=>'Gestión humana'],
            *['name'=>'Enviar documentos de contratación','category'=>'Gestión humana'],
            *['name'=>'Lista de documentos','category'=>'Otros'],
            *['name'=>'Ver documentos','category'=>'Otros'],
            *['name'=>'Crear documentos','category'=>'Otros'],
            *['name'=>'Editar documentos','category'=>'Otros'],
            *['name'=>'Eliminar documentos','category'=>'Otros'],
            *['name'=>'Descargar documentos','category'=>'Otros'],
            *['name'=>'Editar contrato','category'=>'Gestión humana'],
            *['name'=>'Eliminar formato de permisos de trabajo','category'=>'Gestión humana'],
            *['name'=>'Eliminar formato de inspecciones de equipos de protección contra caídas','category'=>'Gestión humana'],
            *['name'=>'Eliminar formato de inspecciones detalladas de vehículos','category'=>'Logística e infraestructura'],
            *['name'=>'Eliminar formato de revisión y asignación de herramientas','category'=>'Ejecución de obras'],
            *['name'=>'Eliminar formato de entrega de dotación personal','category'=>'Gestión humana'],
            *['name'=>'Eliminar formato de listas de verificación para el mantenimiento de los computadores','category'=>'Logística e infraestructura'],
            *['name'=>'Eliminar formato de solicitud de permisos laborales o notificaciones de incapacidad médica','category'=>'Gestión humana'],
            *['name'=>'Exportar usuarios a excel','category'=>'Gestión humana'],
            *['name'=>'CVS Lista de ventas','category'=>'CVS'],
            *['name'=>'CVS Exportar reporte de ventas','category'=>'CVS'],
            *['name'=>'CVS Crear ventas','category'=>'CVS'],
            *['name'=>'CVS Ver ventas','category'=>'CVS'],
            *['name'=>'CVS Cancelar ventas','category'=>'CVS'],
            *['name'=>'CVS Lista de recibos por pagar','category'=>'CVS'],
            *['name'=>'CVS Pagar recibos','category'=>'CVS'],
            *['name'=>'CVS Lista de clientes','category'=>'CVS'],
            *['name'=>'CVS Ver clientes','category'=>'CVS'],
            *['name'=>'CVS Lista de móviles','category'=>'CVS'],
            *['name'=>'CVS Crear móviles','category'=>'CVS'],
            *['name'=>'CVS Ver móviles','category'=>'CVS'],
            *['name'=>'CVS Editar móviles','category'=>'CVS'],
            *['name'=>'CVS Lista de sim cards','category'=>'CVS'],
            *['name'=>'CVS Crear sim cards','category'=>'CVS'],
            *['name'=>'CVS Ver sim cards','category'=>'CVS'],
            *['name'=>'CVS Editar sim cards','category'=>'CVS'],
            *['name'=>'CVS Lista de accesorios','category'=>'CVS'],
            *['name'=>'CVS Crear accesorios','category'=>'CVS'],
            *['name'=>'CVS Ver accesorios','category'=>'CVS'],
            *['name'=>'CVS Editar accesorios','category'=>'CVS'],
            *['name'=>'CVS Lista de sedes','category'=>'CVS'],
            *['name'=>'CVS Crear sedes','category'=>'CVS'],
            *['name'=>'CVS Ver sedes','category'=>'CVS'],
            *['name'=>'CVS Editar sedes','category'=>'CVS'],
            *['name'=>'CVS Lista de tipos de sim cards','category'=>'CVS'],
            *['name'=>'CVS Crear tipos de sim cards','category'=>'CVS'],
            *['name'=>'CVS Ver tipos de sim cards','category'=>'CVS'],
            *['name'=>'CVS Editar tipos de sim cards','category'=>'CVS'],
            *['name'=>'CVS Lista de activaciones','category'=>'CVS'],
            *['name'=>'CVS Crear activaciones','category'=>'CVS'],
            *['name'=>'CVS Ver activaciones','category'=>'CVS'],
            *['name'=>'CVS Editar activaciones','category'=>'CVS'],
            *['name'=>'CVS Lista de categoría de accesorios','category'=>'CVS'],
            *['name'=>'CVS Crear categoría de accesorios','category'=>'CVS'],
            *['name'=>'CVS Ver categoría de accesorios','category'=>'CVS'],
            *['name'=>'CVS Editar categoría de accesorios','category'=>'CVS'],
            *['name'=>'CVS Lista de publicidades','category'=>'CVS'],
            *['name'=>'CVS Crear publicidades','category'=>'CVS'],
            *['name'=>'CVS Ver publicidades','category'=>'CVS'],
            *['name'=>'CVS Editar publicidades','category'=>'CVS'],
            *['name'=>'CVS Finalizar ventas','category'=>'CVS'],
            *['name'=>'Lista de actividades de proyectos','category'=>'Ejecución de obras'],
            *['name'=>'Ver actividades de proyecto','category'=>'Ejecución de obras'],
            *['name'=>'Crear actividades de proyecto','category'=>'Ejecución de obras'],
            *['name'=>'Editar actividades de proyecto','category'=>'Ejecución de obras'],
            *['name'=>'Lista de consumibles para proyectos','category'=>'Ejecución de obras'],
            *['name'=>'Ver consumibles para proyectos','category'=>'Ejecución de obras'],
            *['name'=>'Crear consumibles para proyectos','category'=>'Ejecución de obras'],
            *['name'=>'Editar consumibles para proyectos','category'=>'Ejecución de obras'],
            *['name'=>'Lista de materiales para proyectos','category'=>'Ejecución de obras'],
            *['name'=>'Ver materiales para proyectos','category'=>'Ejecución de obras'],
            *['name'=>'Crear materiales para proyectos','category'=>'Ejecución de obras'],
            *['name'=>'Editar materiales para proyectos','category'=>'Ejecución de obras'],
            *['name'=>'Lista de comisiones para técnicos de proyectos','category'=>'Ejecución de obras'],
            *['name'=>'Crear comisiones para técnicos de proyectos','category'=>'Ejecución de obras'],
            *['name'=>'Editar comisiones para técnicos de proyectos','category'=>'Ejecución de obras'],
            *['name'=>'Lista de comisiones para coordinadores de proyectos','category'=>'Ejecución de obras'],
            *['name'=>'Ver comisiones de control de proyectos','category'=>'Ejecución de obras'],
            *['name'=>'Crear comisiones de control de proyectos','category'=>'Ejecución de obras'],
            *['name'=>'Editar comisiones de control de proyectos','category'=>'Ejecución de obras'],
            *['name'=>'CVS Lista de servicios Claro','category'=>'CVS'],
            *['name'=>'CVS Ver servicios Claro','category'=>'CVS'],
            *['name'=>'CVS Crear servicios Claro','category'=>'CVS'],
            *['name'=>'CVS Editar servicios Claro','category'=>'CVS'],
            *['name'=>'CVS Editar ventas','category'=>'CVS'],
            *['name'=>'CVS Generar corte de pago caja','category'=>'CVS'],
            *['name'=>'CCJL Crear rentas','category'=>'CCJL'],
            *['name'=>'CCJL Ver rentas','category'=>'CCJL'],
            *['name'=>'CCJL Editar rentas','category'=>'CCJL'],
            *['name'=>'CCJL Ver clientes','category'=>'CCJL'],
            *['name'=>'CCJL Editar clientes','category'=>'CCJL'],
            *['name'=>'CCJL Ver canons','category'=>'CCJL'],
            *['name'=>'CCJL Editar canons','category'=>'CCJL'],
            *['name'=>'CCJL Crear servicios','category'=>'CCJL'],
            *['name'=>'CCJL Ver servicios','category'=>'CCJL'],
            *['name'=>'CCJL Editar servicios','category'=>'CCJL'],
            *['name'=>'CCJL Crear administraciones','category'=>'CCJL'],
            *['name'=>'CCJL Ver administraciones','category'=>'CCJL'],
            *['name'=>'CCJL Editar Administraciones','category'=>'CCJL'],
            *['name'=>'CCJL Lista de rentas','category'=>'CCJL'],
            *['name'=>'CCJL Lista de clientes','category'=>'CCJL'],
            *['name'=>'CCJL Lista de canons','category'=>'CCJL'],
            *['name'=>'CCJL Lista de servicios','category'=>'CCJL'],
            *['name'=>'CCJL Lista de administraciones','category'=>'CCJL'],
            *['name'=>'CCJL Pagar rentas','category'=>'CCJL'],
            *['name'=>'CCJL Recordar pago de rentas','category'=>'CCJL'],
            *['name'=>'CCJL Crear canons','category'=>'CCJL'],
            *['name'=>'Lista de indicadores','category'=>'Dirección'],
            *['name'=>'Crear indicadores','category'=>'Dirección'],
            *['name'=>'Informe de indicadores','category'=>'Dirección'],
            *['name'=>'Seguimiento de indicadores','category'=>'Dirección'],
            *['name'=>'Administración de indicadores','category'=>'Dirección'],
            *['name'=>'CVS Lista de todas las ventas','category'=>'CVS'],
            *['name'=>'CVS Eliminar móviles','category'=>'CVS'],
            *['name'=>'CVS Eliminar sim cards','category'=>'CVS'],
            *['name'=>'CVS Eliminar servicios Claro','category'=>'CVS'],
            *['name'=>'CVS Eliminar accesorios','category'=>'CVS'],
            *['name'=>'Ver computadores del inventario','category'=>'Logística e infraestructura'],
            *['name'=>'Editar computadores del inventario','category'=>'Logística e infraestructura'],
            *['name'=>'Eliminar computadores del inventario','category'=>'Logística e infraestructura'],
            *['name'=>'Crear computadores al inventario','category'=>'Logística e infraestructura'],
            *['name'=>'Lista de computadores del inventario','category'=>'Logística e infraestructura'],
            *['name'=>'Exportar bonificaciones de permisos de trabajo','category'=>'Gestión humana'],
            *['name'=>'Lista de tipos de cartelera','category'=>'Otros'],
            *['name'=>'Crear tipos de cartelera','category'=>'Otros'],
            *['name'=>'Editar tipos de cartelera','category'=>'Otros'],
            *['name'=>'Ver tipos de cartelera','category'=>'Otros'],
            *['name'=>'Eliminar tipos de cartelera','category'=>'Otros'],
            *['name'=>'Reactivar porcentaje de proyectos','category'=>'Ejecución de obras'],
            *['name'=>'Suspender proyectos','category'=>'Ejecución de obras'],
            *['name'=>'Reactivar proyectos','category'=>'Ejecución de obras'],
            *['name'=>'Terminar proyectos','category'=>'Ejecución de obras'],
            *['name'=>'Descargar orden de bodega','category'=>'Ejecución de obras'],
            *['name'=>'Descargar marquillas','category'=>'Ejecución de obras'],
            *['name'=>'Ver comisiones para técnicos de proyectos','category'=>'Ejecución de obras'],
            *['name'=>'Aprobar reporte de novedades de nómina y horas extras','category'=>'Dirección'],
            *['name'=>'Digitar reporte de novedades de nómina y horas extras','category'=>'Gestión humana'],
            *['name'=>'Descargar lista de pago de reporte de novedades de nómina y horas extras','category'=>'Gestión humana'],
            *['name'=>'Eliminar formato de reporte de novedades de nómina y horas extras','category'=>'Gestión humana'],
            *['name'=>'Consultar reporte de novedades de nómina y horas extras','category'=>'Gestión humana'],
            *['name'=>'Lista de proyectos de desmonte','category'=>'Ejecución de obras'],
            *['name'=>'Crear proyectos de desmonte','category'=>'Ejecución de obras'],
            *['name'=>'Eliminar proyectos de desmonte','category'=>'Ejecución de obras'],
            *['name'=>'Ver proyectos de desmonte','category'=>'Ejecución de obras'],
            *['name'=>'Editar proyectos de desmonte','category'=>'Ejecución de obras'],
            *['name'=>'Aprobar proyectos de desmonte','category'=>'Dirección'],
            *['name'=>'Lista de proyectos de MINTIC','category'=>'Ejecución de obras'],
            *['name'=>'Crear proyectos de MINTIC','category'=>'Ejecución de obras'],
            *['name'=>'Eliminar proyectos de MINTIC','category'=>'Ejecución de obras'],
            *['name'=>'Ver proyectos de MINTIC','category'=>'Ejecución de obras'],
            *['name'=>'Editar proyectos de MINTIC','category'=>'Ejecución de obras'],
            *['name'=>'Aprobar proyectos de MINTIC','category'=>'Dirección'],
            *['name'=>'Lista de bonificaciones de permisos de trabajo','category'=>'Gestión humana'],
            *['name'=>'Crear corte bonificaciones de permisos de trabajo','category'=>'Gestión humana'],
            *['name'=>'Editar bonificaciones de permisos de trabajo','category'=>'Gestión humana'],
            *['name'=>'Ver bonificaciones de permisos de trabajo','category'=>'Gestión humana'],
            *['name'=>'Terminar contratación de usuarios','category'=>'Gestión humana'],
            *['name'=>'Crear usuarios en hoja de vida','category'=>'Gestión humana'],
            *['name'=>'Aprobar bonificaciones de permisos de trabajo','category'=>'Dirección'],
            *['name'=>'Exportar proyectos de desmonte','category'=>'Ejecución de obras'],
            *['name'=>'Lista de proyectos de rutas','category'=>'Ejecución de obras'],
            *['name'=>'Crear proyectos de rutas','category'=>'Ejecución de obras'],
            *['name'=>'Eliminar proyectos de rutas','category'=>'Ejecución de obras'],
            *['name'=>'Ver proyectos de rutas','category'=>'Ejecución de obras'],
            *['name'=>'Editar proyectos de rutas','category'=>'Ejecución de obras'],
            *['name'=>'Aprobar proyectos de rutas','category'=>'Ejecución de obras'],
            *['name'=>'Lista de vehículos del inventario','category'=>'Logística e infraestructura'],
            *['name'=>'Crear vehículos al inventario','category'=>'Logística e infraestructura'],
            *['name'=>'Ver vehículos del inventario','category'=>'Logística e infraestructura'],
            *['name'=>'Editar vehículos del inventario','category'=>'Logística e infraestructura'],
            *['name'=>'Eliminar vehículos del inventario','category'=>'Logística e infraestructura'],
            *['name'=>'Aprobar retiro de cesantías','category'=>'Gestión humana'],
            *['name'=>'Eliminar solicitud de retiro de cesantías','category'=>'Gestión humana'],
            *['name'=>'Digitar solicitud de retiro de cesantías','category'=>'Gestión humana'],
            *['name'=>'Consultar retiro de cesantías','category'=>'Gestión humana'],
            *['name'=>'Lista de inventarios de consumibles en bodega','category'=>'Ejecución de obras'],
            *['name'=>'Crear consumible del inventario','category'=>'Ejecución de obras'],
            *['name'=>'Editar consumible del inventario','category'=>'Ejecución de obras'],
            *['name'=>'Ver consumible del inventario','category'=>'Ejecución de obras'],
            *['name'=>'Eliminar consumible del inventario','category'=>'Ejecución de obras'],
            *['name'=>'Lista de inventarios de equipos Mintic','category'=>'Ejecución de obras'],
            *['name'=>'Crear equipo al inventario Mintic','category'=>'Ejecución de obras'],
            *['name'=>'Editar equipo al inventario Mintic','category'=>'Ejecución de obras'],
            *['name'=>'Ver equipo al inventario Mintic','category'=>'Ejecución de obras'],
            *['name'=>'Eliminar equipo al inventario Mintic','category'=>'Ejecución de obras'],
            *['name'=>'Ver implementación proyectos de MINTIC','category'=>'Ejecución de obras'],
            *['name'=>'Crear asiganción de implemetación de MINTIC','category'=>'Ejecución de obras'],
            *['name'=>'Editar asiganción de implemetación de MINTIC','category'=>'Ejecución de obras'],
            *['name'=>'Ejecutar asiganción de implemetación de MINTIC','category'=>'Ejecución de obras'],
            *['name'=>'Ver asiganción de implemetación de MINTIC','category'=>'Ejecución de obras'],
            *['name'=>'Eliminar asiganción de implemetación de MINTIC','category'=>'Ejecución de obras'],
            *['name'=>'Entregar caja menor manual','category'=>'Gestión humana'],
            *['name'=>'Editar reporte de novedades de nómina y horas extras','category'=>'Gestión humana'],
            *['name'=>'Lista inventario de herramientas','category'=>'Ejecución de obras'],
            *['name'=>'Ver inventario de herramientas','category'=>'Ejecución de obras'],
            *['name'=>'Editar inventario de herramientas','category'=>'Ejecución de obras'],
            *['name'=>'Crear inventario de herramientas','category'=>'Ejecución de obras'],
            *['name'=>'Eliminar inventario de herramientas','category'=>'Ejecución de obras'],
            *['name'=>'Lista de actas','category'=>'Gestión humana'],
            *['name'=>'Crear actas','category'=>'Gestión humana'],
            *['name'=>'Ver actas','category'=>'Gestión humana'],
            *['name'=>'Editar actas','category'=>'Gestión humana'],
            *['name'=>'Descargar actas','category'=>'Gestión humana'],
            *['name'=>'Eliminar actas','category'=>'Gestión humana'],
            *['name'=>'Aprobar solicitudes permisos propios','category'=>'Gestión humana'],
            *['name'=>'Lista de liquidación de prestaciones sociales','category'=>'Gestión humana'],
            *['name'=>'Crear liquidación de prestaciones sociales','category'=>'Otros'],
            *['name'=>'Ver liquidación de prestaciones sociales','category'=>'Otros'],
            *['name'=>'Editar liquidación de prestaciones sociales','category'=>'Otros'],
            *['name'=>'Descargar liquidación de prestaciones sociales','category'=>'Otros'],
            *['name'=>'Aprobar liquidación de prestaciones sociales','category'=>'Otros'],
            *['name'=>'Lista de bonificaciones a administrativos y conductores','category'=>'Otros'],
            *['name'=>'Crear bonificaciones a administrativos y conductores','category'=>'Otros'],
            *['name'=>'Ver bonificaciones a administrativos y conductores','category'=>'Otros'],
            *['name'=>'Editar bonificaciones a administrativos y conductores','category'=>'Otros'],
            *['name'=>'Descargar bonificaciones a administrativos y conductores','category'=>'Otros'],
            *['name'=>'Eliminar bonificaciones a administrativos y conductores','category'=>'Otros'],
            *['name'=>'Aprobar bonificaciones a administrativos y conductores','category'=>'Otros'],
            *['name'=>'Eliminar liquidación de prestaciones sociales','category'=>'Otros'],
            *['name'=>'Lista de formularios','category'=>'Otros'],
            *['name'=>'Ver respuestas de formularios','category'=>'Otros'],
            *['name'=>'Ver formularios','category'=>'Otros'],
            *['name'=>'Editar formularios','category'=>'Otros'],
            *['name'=>'Exportar formularios','category'=>'Otros'],
            *['name'=>'Eliminar formularios','category'=>'Otros'],
            *['name'=>'Copiar enlaces de los formularios','category'=>'Otros'],
            *['name'=>'Crear formularios','category'=>'Otros'],
            *['name'=>'Lista de acciones de mejora','category'=>'Gestión humana'],
            *['name'=>'Crear acciones de mejora','category'=>'Gestión humana'],
            *['name'=>'Ver acciones de mejora','category'=>'Gestión humana'],
            *['name'=>'Editar acciones de mejora','category'=>'Gestión humana'],
            *['name'=>'Descargar acciones de mejora','category'=>'Gestión humana'],
            *['name'=>'Eliminar acciones de mejora','category'=>'Gestión humana'],
            *['name'=>'Adjuntar y ver fotos de proyectos mintic','category'=>'Ejecución de obras'],
            *['name'=>'CCJL Eliminar rentas','category'=>'CCJL'],
            *['name'=>'Crear programacion en frente de trabajo','category'=>'Dirección'],
            *['name'=>'Lista de programaciones en frente de trabajo','category'=>'Dirección'],
            *['name'=>'Editar programaciones en frente de trabajo','category'=>'Dirección'],
            *['name'=>'Ver programaciones en frente de trabajo','category'=>'Dirección'],
            *['name'=>'Editar de Revisión y asignación de herramientas','category'=>'Ejecución de obras'],
            *['name'=>'Tomar asistencia','category'=>'Gestión humana'],
            *['name'=>'Lista de asistencias','category'=>'Gestión humana'],
            *['name'=>'Ver asistencia','category'=>'Gestión humana'],
            *['name'=>'Editar asistencia','category'=>'Gestión humana'],
            *['name'=>'Eliminar asistencia','category'=>'Gestión humana'],
            *['name'=>'Lista de inventario de técnicos','category'=>'Ejecución de obras'],
            *['name'=>'Editar inventario de técnicos','category'=>'Ejecución de obras'],
            *['name'=>'Ver inventario de técnicos','category'=>'Ejecución de obras'],
            *['name'=>'Lista de preguntas de lesiones aprendidas','category'=>'Otros'],
            *['name'=>'Crear preguntas de lesiones aprendidas','category'=>'Otros'],
            *['name'=>'Editar preguntas de lesiones aprendidas','category'=>'Otros'],
            *['name'=>'Eliminar preguntas de lesiones aprendidas','category'=>'Otros'],
            *['name'=>'Ver preguntas de lesiones aprendidas','category'=>'Otros'],
            *['name'=>'Lista de lesiones aprendidas','category'=>'Otros'],
            *['name'=>'Crear lesiones aprendidas','category'=>'Otros'],
            *['name'=>'Editar lesiones aprendidas','category'=>'Otros'],
            *['name'=>'Eliminar lesiones aprendidas','category'=>'Otros'],
            *['name'=>'Ver lesiones aprendidas','category'=>'Otros'],
            *['name'=>'Exportar lesiones aprendidas','category'=>'Otros'],
            *['name'=>'Limpiar valores de bonificaciones y caja menor de técnicos','category'=>'Gestión humana'],
            *['name'=>'Ver toda la información de usuarios','category'=>'Gestión humana'],
            *['name'=>'Digitar prima de servicios','category'=>'Gestión humana'],
            *['name'=>'Aprobar prima de servicios','category'=>'Gestión humana'],
            *['name'=>'Descargar lista de pago de prima de servicios','category'=>'Gestión humana'],
            *['name'=>'Eliminar formato de prima de servicios','category'=>'Gestión humana'],
            *['name'=>'Consultar prima de servicios','category'=>'Gestión humana'],
            *['name'=>'Editar prima de servicios','category'=>'Gestión humana'],
            *['name'=>'Habilitar permisos laborales','category'=>'Gestión humana'],
            *['name'=>'Configuracion de modales de entrada','category'=>'Otros'],
            *['name'=>'Configuración de modales de empleado del mes','category'=>'Otros'],
            *['name'=>'Lista de documentos de conductores','category'=>'Otros'],
            *['name'=>'Crear documentos de conductores','category'=>'Otros'],
            *['name'=>'Ver documentos de conductores','category'=>'Otros'],
            *['name'=>'Editar documentos de conductores','category'=>'Otros'],
            *['name'=>'Exportar documentos de conductores','category'=>'Otros'],
            *['name'=>'Eliminar documentos de conductores','category'=>'Otros'],
            *['name'=>'Lista de controles de documentos de conductores','category'=>'Logística e infraestructura'],
            *['name'=>'Crear controles de documentos de conductores','category'=>'Logística e infraestructura'],
            *['name'=>'Editar controles de documentos de conductores','category'=>'Logística e infraestructura'],
            *['name'=>'Ver controles de documentos de conductores','category'=>'Logística e infraestructura'],
            *['name'=>'Eliminar controles de documentos de conductores','category'=>'Logística e infraestructura'],
            *['name'=>'Lista de caracterización de accidentes de tráncito','category'=>'Logística e infraestructura'],
            *['name'=>'Crear caracterización de accidentes de tráncito','category'=>'Logística e infraestructura'],
            *['name'=>'Editar caracterización de accidentes de tráncito','category'=>'Logística e infraestructura'],
            *['name'=>'Ver caracterización de accidentes de tráncito','category'=>'Logística e infraestructura'],
            *['name'=>'Eliminar caracterización de accidentes de tráncito','category'=>'Logística e infraestructura'],
            *['name'=>'Lista de cortes de multas','category'=>'Logística e infraestructura'],
            *['name'=>'Editar cortes de multas','category'=>'Logística e infraestructura'],
            *['name'=>'Ver cortes de multas','category'=>'Logística e infraestructura'],
            *['name'=>'Descargar evaluación de desempeño','category'=>'Gestión humana'],
            *['name'=>'Lista de cuentas de cobro','category'=>'Gestión humana'],
            *['name'=>'Lista de cuentas de cobro propias','category'=>'Gestión humana'],
            *['name'=>'Generar cuenta de cobro abierta','category'=>'Gestión humana'],
            *['name'=>'Crear cuenta de cobro','category'=>'Gestión humana'],
            *['name'=>'Ver cuenta de cobro','category'=>'Gestión humana'],
            *['name'=>'Aprobar cuenta de cobro','category'=>'Gestión humana'],
            *['name'=>'Eliminar cuenta de cobro','category'=>'Gestión humana'],
            *['name'=>'Actualizar contraseñas de usuarios','category'=>'Gestión humana'],
            *['name'=>'Eliminar evaluación de desempeños','category'=>'Gestión humana'],
             */
            //EndBlock-20230203

            //Block-20230204 Esteban, Pablo
            // ['name' => 'Lista de paradas de reloj de proyecto MinTIC', 'category' => 'Ejecución de obras'],
            // ['name' => 'Ver parada de reloj de proyecto MinTIC', 'category' => 'Ejecución de obras'],
            // ['name' => 'Crear parada de reloj de proyecto MinTIC', 'category' => 'Ejecución de obras'],
            // ['name' => 'Editar parada de reloj de proyecto MinTIC', 'category' => 'Ejecución de obras'],
            // ['name' => 'Adjuntar y ver fotos a parada de reloj de proyecto MinTIC', 'category' => 'Ejecución de obras'],
            // ['name' => 'Exportar parada de reloj de proyecto MinTIC', 'category' => 'Ejecución de obras'],
            // ['name' => 'Eliminar parada de reloj de proyecto MinTIC', 'category' => 'Ejecución de obras'],
            // ['name' => 'Lista de mantenimiento de proyecto MinTIC', 'category' => 'Ejecución de obras'],
            // ['name' => 'Ver mantenimiento de proyecto MinTIC', 'category' => 'Ejecución de obras'],
            // ['name' => 'Crear mantenimiento de proyecto MinTIC', 'category' => 'Ejecución de obras'],
            // ['name' => 'Editar mantenimiento de proyecto MinTIC', 'category' => 'Ejecución de obras'],
            // ['name' => 'Adjuntar y ver fotos a mantenimiento de proyecto MinTIC', 'category' => 'Ejecución de obras'],
            // ['name' => 'Exportar mantenimiento de proyecto MinTIC', 'category' => 'Ejecución de obras'],
            // ['name' => 'Eliminar mantenimiento de proyecto MinTIC', 'category' => 'Ejecución de obras'],
            // ['name' => 'Lista de implementaciones proyectos de MinTIC', 'category' => 'Ejecución de obras'],
            // ['name' => 'Adjuntar y ver fotos TSS', 'category' => 'Ejecución de obras'],
            // ['name' => 'Adjuntar y ver fotos de instalación', 'category' => 'Ejecución de obras'],
            //EndBlock-20230204

            //Block-20230213 Pablo, Esteban
            // ['name' => 'Crear kits', 'category' => 'Ejecución de obras'],
            // ['name' => 'Ver kits', 'category' => 'Ejecución de obras'],
            // ['name' => 'Editar Kits', 'category' => 'Ejecución de obras'],
            // ['name' => 'Editar todos los Kits', 'category' => 'Ejecución de obras'],
            // ['name' => 'Eliminar Kits', 'category' => 'Ejecución de obras'],
            // ['name' => 'Eliminar todos los Kits', 'category' => 'Ejecución de obras'],
            // ['name' => 'Ver asignación', 'category' => 'Ejecución de obras'],
            // ['name' => 'Editar asignación', 'category' => 'Ejecución de obras'],
            // ['name' => 'Crear asignación', 'category' => 'Ejecución de obras'],
            // ['name' => 'Revisar asignación', 'category' => 'Ejecución de obras'],
            // ['name' => 'Ver revisión', 'category' => 'Ejecución de obras'],
            // ['name' => 'Crear revisión', 'category' => 'Ejecución de obras'],
            //EndBlock-20230213

            //Block-20230219 Esteban
            // ['name' => 'Lista de kits', 'category' => 'Ejecución de obras'],
            //EndBlock-20230219 Esteban
        ];

        foreach ($permissions as $permission) {
            Permission::create(['name' => $permission['name'], 'category' => $permission['category']]);
        }
    }
}
